typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/4wvhzvwmv2rnwgcg0sadhs769hky28xk-zsh-5.9.1/share/zsh/$ZSH_VERSION/help"

source /nix/store/lja33bji6aahyvpr1s82wsjnhjd0nhq0-zsh-autosuggestions-0.7.1/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git docker tmux emacs rust command-not-found)


source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="11111"
SAVEHIST="3000"

HISTFILE="/home/owlenz/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

# Set shell options
set_opts=(
  HIST_FCNTL_LOCK EXTENDED_HISTORY HIST_IGNORE_ALL_DUPS HIST_IGNORE_DUPS
  HIST_IGNORE_SPACE SHARE_HISTORY autocd NO_APPEND_HISTORY
  NO_HIST_EXPIRE_DUPS_FIRST NO_HIST_FIND_NO_DUPS NO_HIST_SAVE_NO_DUPS
)
for opt in "${set_opts[@]}"; do
  setopt "$opt"
done
unset opt set_opts

bindkey -v
DISABLE_MAGIC_FUNCTIONS="true"
export PS1="%F{#FD43B7}%n%f@%F{cyan}%m%f-> %1~ $ "

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"
# npm
export PATH="$HOME/.npm-global/bin:$PATH"
# cargo
export PATH="$HOME/.cargo/bin:$PATH"

eval "$(/nix/store/gv6dc61q6sprcm3hr69yxnwjn3gwcvsc-direnv-2.37.1/bin/direnv hook zsh)"

alias -- ..='cd ..'
alias -- barC='cd ~/.config/waybar/ ; emacsclient -c'
alias -- hyprC='emacsclient -c ~/.config/hypr/hyprland.conf'
alias -- i3C='cd ~/.config/i3/ ; emacsclient -c'
alias -- kittyC='emacsclient -c ~/.config/kitty/kitty.conf'
alias -- ll='eza -bglF --icons'
alias -- ls='eza --icons=always --group-directories-first'
alias -- nivm=nvim
alias -- nlp='nix-store --query --requisites /run/current-system | cut -d- -f2- | sort -u'
alias -- notes='cd ~/Documents/notes; nvim'
alias -- nr='sudo nixos-rebuild switch'
alias -- nrf='sudo nixos-rebuild switch --flake ~/dotfiles'
alias -- nsp='nix search nixpkgs'
alias -- nvimC='cd ~/.config/nvim/ ;  emacsclient -c nvim'
alias -- passC='cat ~/Documents/xdd/pass | wl-copy'
alias -- pick='hyprpicker | tail -c +2 | head -c -1 |wl-copy'
alias -- starC='emacsclient -c ~/.config/starship/starship.toml'
alias -- tmuxC='emacsclient -c ~/.tmux.conf'
alias -- tree='eza --tree --icons'
alias -- vim=nvim
alias -- vimC='cd ~/.config/nvim/ ; emacsclient -c nvim'
alias -- xpick='xcolor | xclip -sel clip'
alias -- zshC='emacsclient -c ~/.zshrc'
source /nix/store/wjfysmv7d7mc00nh8ihn26k3q40fvk1b-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)


